env:
  global:
    - CC_TEST_REPORTER_ID=b2b9246d8ddc35c6ddd5c683518cd97e3eab506d9f56f16194af7092537229b7
language: python
email:
    recipients:
      - lmalina@cern.ch
    on_success: always
    on_failure: always
python:
 - "3.8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - pytest --cov-report xml --cov=omc3 tests/unit tests/accuracy
 - travis-sphinx build --source=doc/ --nowarn
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
 - travis-sphinx deploy
